# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat_stream.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'chat_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63hat_stream.proto\x12\x04\x63hat\"\x86\x02\n\x0b\x43hatMessage\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x12\n\nmessage_id\x18\x02 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\x12\x11\n\tsender_id\x18\x04 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x05 \x01(\t\x12\'\n\x0cmessage_type\x18\x06 \x01(\x0e\x32\x11.chat.MessageType\x12)\n\x0ctext_content\x18\x07 \x01(\x0b\x32\x11.chat.TextContentH\x00\x12+\n\raudio_content\x18\x08 \x01(\x0b\x32\x12.chat.AudioContentH\x00\x42\t\n\x07\x63ontentJ\x04\x08\t\x10\x10\"!\n\x0bTextContent\x12\x0c\n\x04text\x18\x01 \x01(\tJ\x04\x08\x02\x10\x06\"`\n\x0c\x41udioContent\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12!\n\x06\x66ormat\x18\x02 \x01(\x0e\x32\x11.chat.AudioFormat\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\rJ\x04\x08\x04\x10\x0b*Z\n\x0bMessageType\x12\x1c\n\x18MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n\x11MESSAGE_TYPE_TEXT\x10\x01\x12\x16\n\x12MESSAGE_TYPE_AUDIO\x10\x02*\x90\x01\n\x0b\x41udioFormat\x12\x1c\n\x18\x41UDIO_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n\x11\x41UDIO_FORMAT_OPUS\x10\x01\x12\x1a\n\x16\x41UDIO_FORMAT_WEBM_OPUS\x10\x02\x12\x14\n\x10\x41UDIO_FORMAT_MP3\x10\x03\x12\x1a\n\x16\x41UDIO_FORMAT_PCM_16KHZ\x10\x04\x42\x37\n\x16\x63om.yourorg.chat.protoZ\x1dgithub.com/yourorg/chat/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.yourorg.chat.protoZ\035github.com/yourorg/chat/proto'
  _globals['_MESSAGETYPE']._serialized_start=425
  _globals['_MESSAGETYPE']._serialized_end=515
  _globals['_AUDIOFORMAT']._serialized_start=518
  _globals['_AUDIOFORMAT']._serialized_end=662
  _globals['_CHATMESSAGE']._serialized_start=28
  _globals['_CHATMESSAGE']._serialized_end=290
  _globals['_TEXTCONTENT']._serialized_start=292
  _globals['_TEXTCONTENT']._serialized_end=325
  _globals['_AUDIOCONTENT']._serialized_start=327
  _globals['_AUDIOCONTENT']._serialized_end=423
# @@protoc_insertion_point(module_scope)
